# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-linux:
    name: Build Linux Executables
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Cache APT Packages
        uses: awalsh128/cache-apt-pkgs-action@v1.3.0
        with:
          packages: libxxf86vm-dev libx11-dev libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev libgl1-mesa-dev
          version: 1.0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

#      - name: Install dependencies
#        run: |
#          sudo apt-get update
#          sudo apt-get install -y build-essential libxxf86vm-dev libx11-dev libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev libgl1-mesa-dev

      - name: Build Client
        run: CGOENABLED=1 go build -o linux_client -tags client .
        working-directory: /home/runner/work/voxel-combat-revolved/voxel-combat-revolved/

      - name: Build Server
        run: CGOENABLED=1 go build -o linux_server -tags server . && ls -lah linux*
        working-directory: /home/runner/work/voxel-combat-revolved/voxel-combat-revolved/

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            /home/runner/work/voxel-combat-revolved/voxel-combat-revolved/linux_server
            /home/runner/work/voxel-combat-revolved/voxel-combat-revolved/linux_client